<select class="input select-plate select-province">
	<option value="01">京</option>
	<option value="02">津</option>
	<option value="03">沪</option>
	<option value="04">渝</option>
	<option value="05">冀</option>
	<option value="06">豫</option>
	<option value="07">云</option>
	<option value="08">辽</option>
	<option value="09">黑</option>
	<option value="10">湘</option>
	<option value="11">皖</option>
	<option value="12">鲁</option>
	<option value="13">新</option>
	<option value="14">苏</option>
	<option value="15">浙</option>
	<option value="16">赣</option>
	<option value="17">鄂</option>
	<option value="18">桂</option>
	<option value="19">甘</option>
	<option value="20">晋</option>
	<option value="21">蒙</option>
	<option value="22">陕</option>
	<option value="23">吉</option>
	<option value="24">闽</option>
	<option value="25">贵</option>
	<option value="26" selected="true">粤</option>
	<option value="27">川</option>
	<option value="28">青</option>
	<option value="29">藏</option>
	<option value="30">琼</option>
	<option value="31">宁</option>
</select>