<select class="input select-color">
	<option value="01">大型汽车</option>
	<option value="02" selected="true">小型汽车</option>
	<option value="03">使馆汽车</option>
	<option value="04">领馆汽车</option>
	<option value="05">境外汽车</option>
	<option value="06">外籍汽车</option>
	<option value="07">普通摩托车</option>
	<option value="08">轻便摩托车</option>
	<option value="09">使馆摩托车</option>
	<option value="10">领馆摩托车</option>
	<option value="11">境外摩托车</option>
	<option value="12">外籍摩托车</option>
	<option value="13">低速车</option>
	<option value="14">拖拉机</option>
	<option value="15">挂车</option>
	<option value="16">教练车</option>
	<option value="17">教练摩托车</option>
	<option value="18">试验汽车</option>
	<option value="19">试验摩托车</option>
	<option value="20">临时入境汽车</option>
	<option value="21">临时入境摩托车</option>
	<option value="22">临时行驶车</option>
	<option value="23">警用汽车</option>
	<option value="24">警用摩托</option>
	<option value="25">原农机号牌车</option>
	<option value="26">香港入出境车</option>
	<option value="27">澳门入出境车</option>
	<option value="31">武警号牌</option>
	<option value="32">军队号牌</option>
	<option value="99">其他号牌</option>
</select>